### ISSUE TITLE
Ignoring __setitem__ method of class Params

### ISSUE THREAD

**Issue by ZhuBaohe** [kpe/py-params#1]
https://github.com/kpe/py-params/blob/77d6f99f7eb4618ca098eeee9dbc633369735044/params/params.py#L27

The above statement works fine and doesn't raise an AttributeError.

For example,  the codes
```
class TestParams(Params):
    param_a = 'a'
    param_b = True
p = TestParams(param_c=10)
p.update(param_d=20)
print(p)
```
result in
`{'param_a': 'a', 'param_b': True, 'param_c': 10, 'param_d': 20}`.

So accessing parameters not defined as class level variable may be possible.

I think the reason is that when subclassing built-in dict,  __setitem __ override is ignored by the ___init __ and ___update __ methods of the built-in dict. 

See the book  [Fluent Python](http://shop.oreilly.com/product/0636920032519.do)    (_Subclassing Built-In Types Is Tricky_  in   _Chapter 12 Inheritance: For Good or For Worse_ ).

That book also suggests that "_Instead of subclassing the built-ins, derive your classes from the collections module using UserDict, UserList, and UserString, which are designed to be easily extended_". (Page 349)

**Comment by kpe** [comment]
@ZhuBaohe -- thank you very much for your observations. I'll take care soon.
This must have gone broken at some point along the way (edit: it seems it has been omitted from the beginning, thanks!).
